---
- name: Start VM to build ansible on. 
  hosts: localhost
  tasks:
    - name: Start the vm
      shell: |
        set -ex
        # I use hyper-v from WSL. 
        powershell.exe Start-VM -Name {{ vm_name }}
    - name: Wait for host. Through a jumphost as the vm only contains an external network, and isnt directly reachable from WSL
      delegate_to: "{{ jump_host }}"
      wait_for:
        host: "{{ host_ip }}"
        port: 22


- hosts: dev
  remote_user: "{{ user_name }}"
  become: yes
  tasks:
    - name: update
      shell: |
        dpkg --configure -a # It seems all to common that an apt update fails mid-way. This will correct it.
        apt update -y
        apt upgrade -y
    - name: Install Dependencies. Some are possibly not required.
      package:
        name:
          - mlocate # Optional
          - bc
          - bison
          - build-essential
          - ccache
          - curl
          - flex
          - g++-multilib
          - gcc-multilib
          - git
          - gnupg
          - gperf
          - imagemagick
          - lib32ncurses5-dev
          - lib32readline-dev
          - lib32z1-dev
          - liblz4-tool
          - libncurses5-dev
          - libsdl1.2-dev
          - libssl-dev
          - libwxgtk3.0-gtk3-dev
          - libxml2
          - libxml2-utils
          - lzop
          - pngcrush
          - rsync
          - schedtool
          - squashfs-tools
          - xsltproc
          - zip
          - zlib1g-dev
          - openjdk-11-jre-headless
          - python3-pip
          - lib32ncurses-dev
          - lib32ncurses6
          - lib32ncursesw6
          - libncurses-dev
          - libncurses5-dev
          - libncurses5
          - libncurses6
          - libncursesw5-dev
          - libncursesw6
          - ncurses-base
          - ncurses-bin
          - ncurses-term
        state: latest
      async: 1000
      poll: 10

- name: Build android. Not as root. 
  hosts: dev
  remote_user: "{{user_name}}"
  roles:
    - joyeuse

- name: Turn off the VM. Turn off Host
  hosts: localhost
  tasks:
    - name: Stop the VM. This seems to issue a shutdown.
      shell: |
        set -ex
        # I use hyper-v from WSL. 
        powershell.exe Stop-VM -Name {{ vm_name }}
        # Turn off host. Just to make sure the VM settles - we'll leave the one mintue timer
        powershell.exe shutdown.exe /s 
